### ISSUE TITLE
Use class alias

### ISSUE THREAD

**Issue by omalleyt12** [keras-team/keras-autodoc#16]
Hi @gabrieldemarmiesse , is there a way to have a class documentation use its alias rather than its actual class name?

I.e. we have `keratuner.tuners.randomsearch.RandomSearchOracle` but we also have this aliased as `kerastuner.oracles.RandomSearch`. Is there a way to make the second name be the display name in documentation?

**Comment by gabrieldemarmiesse** [comment]
Currently, we use attributes like `__name__` and `__module__` to make the start of the signature. Making aliases doesn't change it. Would it be possible to override them on your side? It would also make more sense for the user.

**Comment by gabrieldemarmiesse** [comment]
I have a fix in the works, see #26
