### ISSUE TITLE
Functions with wrappers showing as having no arguments

### ISSUE THREAD

**Issue by omalleyt12** [keras-team/keras-autodoc#17]
In particular wrapping a function with `@contextlib.contextmanager` is making it so that the arguments don't show up

Having this issue with `kerastuner.HyperParameters.conditional_scope`

@gabrieldemarmiesse

**Comment by gabrieldemarmiesse** [comment]
Well, if they hide the function parameters behind a `*args, **kwargs` signature, there isn't much we can do. I'll look into it and try to find a workaround.
