### ISSUE TITLE
Docstring of super class doesn't show

### ISSUE THREAD

**Issue by omalleyt12** [keras-team/keras-autodoc#19]
@gabrieldemarmiesse 

I'm seeing an issue where if a docstring exists in the super class but not in the subclass method then it is not showing up at all

**Comment by gabrieldemarmiesse** [comment]
This can be fixed using ` inspect.getdoc` instead of `__doc__`. It's non-trivial because of the docstring parsing being different afterwards, but I'll do it at some point. It's much cleaner anyway.
