### ISSUE TITLE
Display the type hints and default values in the description.

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [keras-team/keras-autodoc#71]
Displaying them in the signature is too heavy. It's better fitted in the description. Same for the return type.
See https://github.com/keras-team/autokeras/pull/957#discussion_r379223556

**Comment by leonoverweel** [comment]
Hey, is there a roadmap for this? Is it something I could help with?

Context: we're trying to switch our [Larq](https://larq.dev) docs ([larq/larq](https://github.com/larq/larq), [larq/zoo](https://github.com/larq/zoo), [larq/compute-engine](https://github.com/larq/compute-engine)) over to keras-autodoc (and it's cleaning up our generation code *a ton*!) but for now we're blocked by the signatures containing very long type hints and becoming less readble; see larq/docs#68.

Thanks for all your work on this package!

**Comment by gabrieldemarmiesse** [comment]
If you want to make a pull request, I'll be happy to review it. Currently I'm quite busy with tensorflow addons, so I won't implement it myself in the near term. We're using sphynx to generate the type hints. So grabbing them shouldn't be too hard. One thing that may be a bit harder is that we don't dectect the arguments currently, we just use a regex to transform them. The interesting piece of code is here: https://github.com/keras-team/keras-autodoc/blob/master/keras_autodoc/docstring.py#L70 

One would need to replace the regex by some plain reading, where if the section is called "Arguments" then you need to match the arguments names to the type hints. It's some work, but definitly not extremely hard.

**Comment by leonoverweel** [comment]
Thanks for the quick reply! I'm getting started on this in a fork; will try to send over a PR tomorrow.

**Comment by gabrieldemarmiesse** [comment]
What's left is to do the alias substitution in the type hints, and we're good to close this pull request.

**Comment by gabrieldemarmiesse** [comment]
This has been fixed.
