### ISSUE TITLE
Can "function" and "class" suffixes in docs headers be removed or become optional?

### ISSUE THREAD

**Issue by leonoverweel** [keras-team/keras-autodoc#82]
Currently Keras Autodoc appends the word "class" to the names of classes in their docs headers ([example in our Larq docs](https://docs.larq.dev/larq/api/layers/#larqlayers), `larq.layers.QuantDense` becomes "QuantDense class") and "function" to the names of functions ([example](https://docs.larq.dev/larq/api/models/)).

We think this adds a bit of unnecessary visual noise/clutter (see larq/docs#118), so I was wondering if this is something we can make optional or remove altogether? I'd be happy to make a PR myself, just wanted to check in before I do. :)

**Comment by gabrieldemarmiesse** [comment]
I'd be in favor of removing them altogether :) sometimes, we want users to use a function as a class constructor and sometimes there are classes that look like functions (being lowercase). So it's confusing if we explicitly say what they are in the docs.
