### ISSUE TITLE
[Question] Pinned Black version

### ISSUE THREAD

**Issue by lgvaz** [keras-team/keras-autodoc#86]
Hi!

In `setup.py` black is pinned to the version `19.10b0`, is that a hard requirement for the documentation to build properly?

I'm using your package as a dependency of mine, and this also requires me to lock the version of black, I tested building the docs with the newest version of black and it seemed to work just fine.

**Comment by gabrieldemarmiesse** [comment]
We pinned it to avoid surprises. But we should keep up with nlack releases. If you make a pull request to bump the version i'll gladly merge it

**Comment by lgvaz** [comment]
Cool! #87 should do it, tell me if you need me to modify anything else as well

If everything works, can I ask for one additional favor? Can you publish the changes to pypi? :sweat_smile: 

Thanks a lot =)

**Comment by gabrieldemarmiesse** [comment]
Sure thing, I'll put it in my TODO list :), it might take a few days.

**Comment by gabrieldemarmiesse** [comment]
0.6.0 released :)
